name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Set up GOPATH
      run: |
        echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
        echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
    
    - name: Check out
      uses: actions/checkout@v2
      with:
          path: src/github.com/hellflame/easy-mail
          
    - name: Install dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v ./...
      
    - name: Run Unit tests
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...
      working-directory: src/github.com/hellflame/easy-mail
    
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    
    - name: Send coverage
      run: goveralls -coverprofile=covprofile -service=github
      working-directory: src/github.com/hellflame/easy-mail
  
